Blog/urls.py
from django.urls import path
from .views import (BlogIndexView, Login, LogOut, ReplyHandler, Registration,
                    UpdateDeleteComment, VotesHandler)

app_name = 'Blog'

urlpatterns = [
    path('',
        BlogIndexView.as_view(),
        name='Blog_index',
        ),
    path(
        'Comment/Delete/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Delete_comment',
        ),
    path(
        'Comment/Update/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Update_comment',
        ),
    path(
        'Login/',
        Login.as_view(),
        name='Login',
        ),
    path(
        'Login/<str:error>/',
        BlogIndexView.as_view(),
        name="Login_error",
        ),
    path(
        'Logout/',
        LogOut.as_view(),
        name='Logout',
        ),
    path(
        'Reply/<str:parent_comment_pk>/',
        ReplyHandler,
        name='Reply',
        ),
    path(
        'Registration/',
        Registration,
        name='Registration',
        ),
    path(
        'Registration/<str:error_type>/',
         BlogIndexView.as_view(),
         name='Registration_error',
        ),
    path(
        'Vote/<int:comment_pk>/<str:vote_type>/',
        VotesHandler,
        name='Vote',
        ),
]

Profile/urls.py
from django.urls import path

from .views import upload_csv,IndexView, SubscriptionHandler, ResumeView, csv_download, load_product_data, SubscriptionHandler_product

app_name = 'Profile'

urlpatterns = [
    path(
        '',
        IndexView.as_view(),
        name='index',
        ),
    path(
        'BNResume/',
        ResumeView,
        name='resume',
        ),
    path(
        'Subscription/',
        SubscriptionHandler,
        name='subscription',
        ),
    path(
        'Product_Subscription/',
        SubscriptionHandler_product,
        name='product-subscription',
        ),
    path(
        'csv_download/',
        csv_download,
        name='csv_download',
        ),
    path(
        'load_product_data/',
        load_product_data,
        name='load_product_data',
        ),
    path(
        'upload_csv',
        upload_csv,
        name='upload_csv'
        ),
]

custom_search/urls.py
from django.urls import path

from .views import IndexView,get_tweetdata
app_name = 'custom_search'

urlpatterns = [
    path(
        '',
        IndexView.as_view(),
        name='index',
        ),
    path(
        'get_tweetdata/',
        get_tweetdata,
        name='get_tweetdata',
        ),
]

main_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
        ),
    path(
        '',
        include('Blog.urls'),
        ),
    path('profile/',
        include('Profile.urls'),
        ),
    path('custom_search/',
        include('custom_search.urls'),
        ),
    path('django_plotly_dash/', 
        include('django_plotly_dash.urls'),
        ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_search/models.py
from django.db import models

# Create your models here.

custom_search/views.py
# *************************************************************************************************************************************************************
# This python file is a view file for the custom_search app. It renders all the needed data in index.html and load_data.html which are under templates/custom_search. 
# *************************************************************************************************************************************************************
from django.shortcuts import render
from .custom_tweet_collector import collect_tweets_for_product
from multiprocessing import Process
import time
import multiprocessing
import heapq
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from main_project.settings import STATIC_DIR
from datetime import date, timedelta
import datetime
import random
from django.utils.safestring import mark_safe
from django.template import Context
from django.template.context import make_context
import re
import urllib.request
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
# *************************************************************************************************************************************************************
class IndexView(TemplateView):
    template_name = 'custom_search/index.html'

#     Function :
#                   get_context_data(**kwargs): Returns the context that is needed to display in "custom_search/index.html"
#     Input : 
#                   None
#     Output :      
#                   Returns the context needed to display in "custom_search/index.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Generates context for the blurb
        # context["statistical_data"] = collect_tweets_for_product()
        # Generates context for the about me section

        return context

# *************************************************************************************************************************************************************
#     Function :
#                   get_tweetdata(request): It collects the twitter statistical data for any keyword by calling function collect_tweets_for_product() renders the load_data.html with this statistical data and returns this as a response to the ajax script which called get_tweetdata from index.html
#     Input : 
#                   request :
#     Output :      
#                   Renders the "custom_search/load_data.html" with context as statistical twitter data for the keywords.
# 	  Note : 		
# 					Here load_data.html is just a collection of div containers and not a comple html doc. So as soon as context is renderd in load_data.html it is dynamically placed appropriately inside index.html.

def get_tweetdata(request):
	# print ("Call to get_tweetdata is successfull")
	context = {}
	# try:
	# 	product_name = request.POST['product_name']
	# 	context["statistical_data"] = collect_tweets_for_product(product_name=product_name)
	# 	context["success_message"] = "Product found"
	# except:
	# 	context["success_message"] = "Databse server error! Product can't be found."

	if request.method == 'POST' and request.is_ajax():
		product_name = request.POST['product_name']
		print ("im here")
		context["statistical_data"] = collect_tweets_for_product(product_name=product_name)
		context["success_message"] = "Product found"
	else:
		print (product_name)
		context["success_message"] = "Databse server error! Product can't be found."

	return render(request,'custom_search/load_data.html',context)

# *************************************************************************************************************************************************************

templates/custom_search/index.html
{% extends "base.html" %}


{% load staticfiles %}
<!-- ************************************************************************************************************************************************************** -->
<!-- This contains the item to be displayed in the nav bar of the custom twitter search page. -->
{% block navigation %}

  <li class="nav-item">
    <a class="nav-link" href="{% url 'Blog:Blog_index' %}"> ホーム
 </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Profile:index' %}"> 製品分析
 </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'custom_search:index' %}"> カスタムTwitter検索
 </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#signup">接触</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url "Blog:Logout" %}">ログアウト</a>
  </li>

{% endblock %}
<!-- ********************************************************************************************************************************************************* -->
{% block scripts %}

{% endblock %}

<!-- Heading Text  -->

{% block heading_text %}{{blurb}}{% endblock %}

<!--*************************************************************************************************************************************************************** -->
<!-- The content contains the items to be displayed as the product analysis entities like graphs, table, twitter analysis, most popular users and etc. It describes the basis content about the product  -->
{% block content %}

<br><br><br>
<!--*************************************************************************************************************************************************************** -->
<!-- Their are two sections inside div container first section contains the search bar for writing the keyword and a script which will run when user clicks on search button.And the second section contains the data to be displayed to the user. -->
<div style="margin-left: 15%;margin-right: 15%;background:white">
  <!-- ********************************************************************************************************************************************************* -->
  <!-- This section contains the serach form for searching the twitter data via keyword. -->
  <section id="search-bar" class="aboutme-section bg-light">
    <div style="background-image: url(https://www.tweetbinder.com/public/images/patterns/home-pattern-right.png);width:100%;height:auto;min-height: 250px;display:block;margin:auto">
      <div>
        <div  class = "row"style = "display: block;margin: auto;text-align:center;width:100%">
          <h6 style = "font-weight: 800;font-size: 1.3rem">Custom Search here</h6>
        </div>
        <br>
        <br>
        <br>
        <div class = "row" style = "display: block;margin-left: 10%;margin-right:10%;text-align:center;width:100%">
          <!-- ************************************************************************************************************************************************* -->
          <!-- Form for custom twitter data search -->
          <form class="form-inline d-flex subscribe-product-form" action="{% url "custom_search:get_tweetdata" %}" method="post">
              {% csrf_token %}
            <div class = "row" style = "width:100%!important;min-height: 50px">
              <div class = "col-8">
                <input name='product_name' type="Product" style = "height:100%;width:100%;" id="product_name" placeholder="Enter Product Name...">
              </div>
              <div class = "col-1">
                <button type="submit" style = "width:100%;height:100% !important;border-radius: 5%!important" class="btn-primary"><i class="fa fa-search-plus" aria-hidden="true"></i></button>
              </div>
            </div>
          </form>
          <!-- ************************************************************************************************************************************************ -->
          <!-- This script will run when user click on search button and it will call get_tweetdata() function in custom_search/views.py which will further load the data and will then render load_data.html with twiiter data to return the html response which will then be placed in Data-bar section.-->
          <script type="text/javascript">
            $(document).ready(function(){
              $('.subscribe-product-form').submit(function(e){
                $('#Data-bar').html("<div id='loading' style='width:100%;min-height:250px;height:auto';background:white;text-align:center><img id='loading-image' src='https://cdn.dribbble.com/users/93293/screenshots/3449220/pqe__1_.gif' alt='Loading...' style='display:block;margin-left:auto;margin-right:auto;align-self:center' /></div>")
                e.preventDefault();
                var this_ = $(this);
                var urlEndpoint = this_.attr('action');
                var formData = this_.serialize();
                console.log(formData)
                $.ajax({
                  async: true,
                  url: urlEndpoint,
                  method: "POST",
                  data: formData,
                  success: function(response){
                    $('#Data-bar').html(response);
                    $('#Data-bar').fadein(slow);
                  },
                })
              })
            })

          </script>
          <!-- *********************************************************************************************************************************************** -->
        </div>
      </div>
    <div>
  </section>
  <br>
  <br>
  <br>
  <!-- ********************************************************************************************************************************************************* -->
  <!-- When index.html will be loaded for first time, below data will be displayed inside section Data-bar but it will will be replaced by load_data.html renderd with twitter data as context via above script when user starts searching for the particular keyword.  -->
  <section id = "Data-bar">
    <div class="row" style = "margin-left: 5%;margin-right: 5%">
      <div class = "col-md-4 col-lg-4">
        <br>
        <div class= "row image-class" style = "margin-left:2%;margin-right:2%;margin-top:2%;margin-bottom:2%;height: 200px;width:200px;align-items: center;margin:auto;display:block;">
          <img src="https://mk0pagerolwgibgwnjg6.kinstacdn.com/wp-content/uploads/Analytics-Dashboard-Circle-200x200.png" style="border-radius: 50%;box-shadow: 0 0 10px green" />
        </div>
        <br><br><br>
        <div class= "row text-class" style = "margin-left:2%;margin-right:2%;margin-top:2%;margin-bottom:2%;align-items: center;margin:auto;display:block;text-align: center;text-shadow: 1px 1px 2px grey">
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Analyse Product Market
          </span>
          <br>
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Analyse sentiment statistics
          </span>
          <br>
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Analyse tweet influence statistics
          </span>
        </div>
      </div>
      <div class = "col-md-4 col-lg-4">
        <br>
        <div class= "row image-class" style = "margin-left:2%;margin-right:2%;margin-top:2%;margin-bottom:2%;height: 200px;width:200px;align-items: center;margin:auto;display:block;">
          <img src="https://www.blastam.com/wp-content/uploads/analytics-strategy-challenge05.png"  style="border-radius: 50%;box-shadow: 0 0 10px blue" />
        </div>
        <br><br><br>
        <div class= "row text-class" style = "margin-left:2%;margin-right:2%;margin-top:2%;margin-bottom:2%;align-items: center;margin:auto;display:block;text-align: center;text-shadow: 1px 1px 2px grey">
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Find what's next
          </span>
          <br>
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Find what's new
          </span>
          <br>
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Find what's future
          </span>
        </div>
      </div>
      <div class = "col-md-4 col-lg-4">
        <br>
        <div class= "row image-class" style = "margin-left:2%;margin-right:2%;margin-top:2%;margin-bottom:2%;height: 200px;width:200px;align-items: center;margin:auto;display:block;">
          <img src="https://6b7o7u172h-flywheel.netdna-ssl.com/wp-content/uploads/2019/05/Influencer-Connector.png"  style="border-radius: 50%;box-shadow: 0 0 10px red" />
        </div>
        <br><br><br>
        <div class= "row text-class" style = "margin-left:2%;margin-right:2%;margin-top:2%;margin-bottom:2%;align-items: center;margin:auto;display:block;text-align: center;;text-shadow: 1px 1px 2px grey">
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Check who is suitable
          </span>
          <br>
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Check who is influencer
          </span>
          <br>
          <span>
            <i class="fa fa-check" aria-hidden="true" style = "color:green!important;"></i>
            &nbsp
            Check who is most active
          </span>
        </div>
      </div>
    
    </div>
  </section>
  <!-- ************************************************************************************************************************************************************** -->
  <br>
  <br>
</div>
<!--*************************************************************************************************************************************************************** -->
<script src="{% static "base/js/Projects.js" %}" charset="utf-8"></script>

{% endblock %}
<!--*************************************************************************************************************************************************************** -->