Blog/urls.py
from django.urls import path
from .views import (BlogIndexView, Login, LogOut, ReplyHandler, Registration,
                    UpdateDeleteComment, VotesHandler)

app_name = 'Blog'

urlpatterns = [
    path('',
        BlogIndexView.as_view(),
        name='Blog_index',
        ),
    path(
        'Comment/Delete/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Delete_comment',
        ),
    path(
        'Comment/Update/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Update_comment',
        ),
    path(
        'Login/',
        Login.as_view(),
        name='Login',
        ),
    path(
        'Login/<str:error>/',
        BlogIndexView.as_view(),
        name="Login_error",
        ),
    path(
        'Logout/',
        LogOut.as_view(),
        name='Logout',
        ),
    path(
        'Reply/<str:parent_comment_pk>/',
        ReplyHandler,
        name='Reply',
        ),
    path(
        'Registration/',
        Registration,
        name='Registration',
        ),
    path(
        'Registration/<str:error_type>/',
         BlogIndexView.as_view(),
         name='Registration_error',
        ),
    path(
        'Vote/<int:comment_pk>/<str:vote_type>/',
        VotesHandler,
        name='Vote',
        ),
]

Profile/urls.py
from django.urls import path

from .views import upload_csv,IndexView, SubscriptionHandler, ResumeView, csv_download, load_product_data, SubscriptionHandler_product

app_name = 'Profile'

urlpatterns = [
    path(
        '',
        IndexView.as_view(),
        name='index',
        ),
    path(
        'BNResume/',
        ResumeView,
        name='resume',
        ),
    path(
        'Subscription/',
        SubscriptionHandler,
        name='subscription',
        ),
    path(
        'Product_Subscription/',
        SubscriptionHandler_product,
        name='product-subscription',
        ),
    path(
        'csv_download/',
        csv_download,
        name='csv_download',
        ),
    path(
        'load_product_data/',
        load_product_data,
        name='load_product_data',
        ),
    path(
        'upload_csv',
        upload_csv,
        name='upload_csv'
        ),
]

custom_search/urls.py
from django.urls import path

from .views import IndexView,get_tweetdata
app_name = 'custom_search'

urlpatterns = [
    path(
        '',
        IndexView.as_view(),
        name='index',
        ),
    path(
        'get_tweetdata/',
        get_tweetdata,
        name='get_tweetdata',
        ),
]

main_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
        ),
    path(
        '',
        include('Blog.urls'),
        ),
    path('profile/',
        include('Profile.urls'),
        ),
    path('custom_search/',
        include('custom_search.urls'),
        ),
    path('django_plotly_dash/', 
        include('django_plotly_dash.urls'),
        ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.text import slugify

class Blurb(models.Model):
    blurb = models.TextField(max_length=275, blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)

class BlogPost(models.Model):
    superuser = models.ForeignKey(
        get_user_model(),
        related_name='blogposts',
        on_delete=models.CASCADE,
        )
    title = models.CharField(max_length=45, blank=False)
    photo = models.ImageField(upload_to="Blog/BlogPost/", blank=True, null=True)
    photo_subtitle = models.TextField(blank=True)
    posted_at = models.DateTimeField(auto_now_add=True)
    body = RichTextField(blank=False, config_name='ckeditor')
    preview = models.CharField(max_length=170, blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True)

    def get_absolute_url(self):
        print(reverse('Blog:blog_index', args=[self.slug]))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta():
        ordering = ["-posted_at"]

class Comment(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        related_name='comments',
        on_delete=models.CASCADE,
        )
    blogpost = models.ForeignKey(
        BlogPost,
        related_name='comments',
        on_delete=models.CASCADE,
        )
    body = RichTextField(blank=False, config_name='ckeditor_comments')
    commented_at = models.DateTimeField(auto_now_add=True)
    comment_date = models.DateField(auto_now_add=True, null=True)
    votes = models.ManyToManyField(get_user_model(), blank=True)
    score = models.IntegerField(default=0)
    is_reply = models.BooleanField(default=False, null=True)
    parent_comment = models.ForeignKey(
        'self',
        related_name='replies',
        null=True,
        on_delete=models.CASCADE,
    )
    reply_body = models.TextField(blank=False, null=True)

    def __str__(self):
        return f'{self.blogpost.title}: {self.commented_at}'

    def increment_vote(self, user, vote_type):

        if user not in self.votes.all(): # User's first time voting
            self.votes.add(user)

            if vote_type == 'upvote':
                self.score += 1
                VoteType.objects.create(
                    user=user,
                    comment=self,
                    vote_type='upvote',
                    )
            elif vote_type == 'downvote':
                self.score -= 1
                VoteType.objects.create(
                    user=user,
                    comment=self,
                    vote_type='downvote',
                    )

        else: # If user had already voted previously
            previous_vote_obj = get_object_or_404(
                VoteType,
                user=user,
                comment=self,
            )
            previous_vote = previous_vote_obj.vote_type
            if vote_type == 'upvote':
                if previous_vote == 'upvote':
                    self.score -= 1
                    vote_type = ''
                elif previous_vote == 'downvote':
                    self.score += 2
                else:
                    self.score += 1
            elif vote_type == 'downvote':
                if previous_vote == 'downvote':
                    self.score += 1
                    vote_type = ''
                elif previous_vote == 'upvote':
                    self.score -= 2
                else:
                    self.score -= 1

            previous_vote_obj.vote_type = vote_type
            previous_vote_obj.save()

        self.save()

    def show_score(self):
        return self.score

    def show_vote_count(self):
        return self.votes.count()

    class Meta:
        ordering = ['-commented_at']
        get_latest_by = 'commented_at'

class VoteType(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        related_name='vote_types',
        on_delete=models.CASCADE,
        )
    comment = models.ForeignKey(
        Comment,
        related_name='vote_types',
        on_delete=models.CASCADE,
        )
    vote_type = models.CharField(max_length=20, blank=True, null=True)

Blog/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Comment
from .mixins import FormFields


class LoginForm(forms.Form, FormFields):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.get_fields():
            self.fields[field].label = ''
            self.fields[field].widget.attrs.update({
                'class': 'login-styles',
                'placeholder': field,
                })

class RegistrationForm(UserCreationForm):
    user_fields = ('username', 'password1', 'password2')

    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.user_fields:
            if field == 'password1':
                placeholder = 'password'
            elif field == 'password2':
                placeholder = 'password confirmation'
            else:
                placeholder = 'username'
            self.fields[field].label = ''
            self.fields[field].widget.attrs.update({
                'class': 'registration-styles',
                'placeholder': placeholder,
                })

class CommentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].label = ''

    class Meta:
        model = Comment
        fields = ('body', )

class EditCommentForm(forms.Form):
    content = forms.CharField(widget=CKEditorWidget(config_name='edit_comment'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].label = ''

Blog/views.py
import re
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LogoutView, LoginView
from django.core import serializers
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView

from .forms import CommentForm, EditCommentForm, LoginForm, RegistrationForm
from .models import BlogPost, Comment

def Registration(request):

    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST)
        username = request.POST['username']
        pw_1 = request.POST['password1']
        pw_2 = request.POST['password2']

        if pw_1 != pw_2:
            return HttpResponseRedirect(
            reverse_lazy('Blog:Registration_error', args=['pw_mismatch'])
            )
        try:
            get_object_or_404(get_user_model(), username=username)
            return HttpResponseRedirect(
            reverse_lazy('Blog:Registration_error', args=['user_exists'])
            )
        except:
            pass

        if registration_form.is_valid():
            new_user = registration_form.save()
        else:
            return HttpResponseRedirect(
            reverse_lazy('Blog:Registration_error', args=['user_exists'])
            )

    return HttpResponseRedirect(reverse_lazy('Blog:Blog_index'))

class Login(LoginView):
    template_name = 'Blog/blog_index.html'

    def get_success_url(self):
        return reverse_lazy('Blog:Blog_index')

    def form_invalid(self, form):
        return HttpResponseRedirect(
            reverse_lazy('Blog:Login_error', args=['login_error'])
        )

class LogOut(LogoutView):
    next_page = reverse_lazy('Blog:Blog_index')

class BlogIndexView(FormView, ListView):
    template_name = 'Blog/blog_index.html'
    context_object_name = 'blogposts'
    paginate_by = 1
    form_class = CommentForm
    redirect_field_name = reverse_lazy('Blog:Blog_index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['login_form'] = LoginForm
        context['registration_form'] = RegistrationForm
        context['edit_comment_form'] = EditCommentForm

        try:
            error_type = self.kwargs['error_type']
            if error_type == 'pw_mismatch':
                context['pw_mismatch'] = True
            elif error_type == 'user_exists':
                context['user_exists'] = True
            elif error_type == 'invalid_fields':
                context['invalid_fields'] = True
        except KeyError:
            pass

        try:
            if self.kwargs['error']:
                context['login_error'] = True
        except KeyError:
            pass

        return context

    def get_queryset(self):
        return BlogPost.objects.all()

    def get_page_number(self, return_type):
        regex = r'\?page=\d*'
        pattern = re.compile(regex)
        referer = self.request.META['HTTP_REFERER']
        try:
            query_str = pattern.search(referer).group(0)
        except AttributeError:
            query_str = '?page=1'

        page_num = query_str[-1]

        if return_type == 'query_string':
            return query_str
        elif return_type == 'page_num':
            return page_num

    def get_success_url(self):
        query_str = self.get_page_number('query_string')
        return reverse_lazy('Blog:Blog_index') + query_str

    def get_blog_post(self):
        paginator = Paginator(self.get_queryset(), 1)
        obj_list = paginator.page(self.get_page_number('page_num'))
        blog_post = obj_list[0]
        return blog_post

    def form_valid(self, form):
        comment_form = CommentForm(self.request.POST)
        comment = comment_form.save(commit=False)
        comment.blogpost = self.get_blog_post()
        comment.user = self.request.user
        comment.save()

        if self.request.is_ajax():
            template_context = {
                'commented': True,
                'comments': self.get_blog_post().comments.all(),
                'user': self.request.user,
                }
            comments = render_to_string(
                'Blog/comments.html',
                context=template_context,
                request=self.request,
                )
            json_context = {'comments': comments}
            return JsonResponse(json_context)

        return super().form_valid(form)

    def form_invalid(self, form):
        return HttpResponseRedirect(self.get_success_url())

def ReplyHandler(request, parent_comment_pk):
    response = HttpResponseRedirect(reverse_lazy('Blog:Blog_index'))

    parent_comment = Comment.objects.get(pk=parent_comment_pk)
    parent_post = parent_comment.blogpost

    if request.method == 'POST':
        Comment.objects.create(
            user=request.user,
            blogpost=parent_post,
            is_reply=True,
            parent_comment=parent_comment,
            reply_body=request.POST['reply_body']
        )

    if request.is_ajax():
        template_context = {
            'replied': True,
            'parent_comment': parent_comment,
        }
        template = render_to_string(
            'Blog/replies.html',
            template_context,
            request=request,
            )
        response = JsonResponse({'replies': template})

    return response

def VotesHandler(request, comment_pk, vote_type):
    response = HttpResponseRedirect(reverse_lazy('Blog:Blog_index'))

    user = request.user
    comment = get_object_or_404(Comment, pk=comment_pk)

    if user.is_authenticated:
        comment.increment_vote(user, vote_type)

    if request.is_ajax():
        json_context = {'score': comment.score, 'id': comment.pk}
        response = JsonResponse(json_context)

    return response

def UpdateDeleteComment(request, comment_pk):
    response = HttpResponseRedirect(reverse_lazy('Blog:Blog_index'))
    path = request.META.get('PATH_INFO')

    comment = get_object_or_404(Comment, pk=comment_pk)
    blogpost = comment.blogpost

    if request.method == 'POST':
        if 'Delete' in path:
            comment.delete()
        elif 'Update' in path:
            if comment.is_reply:
                edit = request.POST.get('edit_body')
                comment.reply_body = edit
                comment.save()
            else:
                edit = request.POST.get('edited-parent-comment')
                comment.body = edit
                comment.save()

    if request.is_ajax():
        template_context = {
            'commented': True,
            'comments': blogpost.comments.all(),
            'user': request.user,
            }
        comment_sec = render_to_string(
            'Blog/comments.html',
            template_context,
            request=request
            )
        response = JsonResponse({'comments': comment_sec})

    return response

templates/Blog/blog_index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

<!-- Navbar -->
{% block navigation %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Blog:Blog_index' %}"> ホーム
 </a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'Profile:index' %}"> 製品分析
 </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'custom_search:index' %}"> カスタムTwitter検索
 </a>
  </li>
  {% endif %}
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#signup">接触</a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url "Blog:Logout" %}">ログアウト</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link sign-up">サインアップ</a>
  </li>
  <li class="nav-item">
    <a class="nav-link log-in">ログイン</a>
  </li>
  {% endif %}

{% endblock %}

<!-- Heading Text -->
{% block heading_text %}{{ blurb.blurb }}{% endblock %}

<!-- Main content -->
{% block content %}
  <section id="about" class="about-section text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-white mb-4" style = "color: black !important;">会社 X </h2>
          <p class="text-white-50" style = "color: black !important;"></p>
        </div>
      </div>
    </div>
  </section>

  <!-- Sign up form -->
  <div class="bg-modal signup"
    {% if pw_mismatch or user_exists or invalid_fields %}
    style="display:flex"
    {% endif %}
    >
    <div class="modal-content-signup" style="margin-left: 10rem !important;margin-right: 10rem !important">
      <div class="close">+</div>
      <div class="login-brand">
        <h2 class="blog-brand">ここでサインアップ</h2>
      </div>
      <div class="registration-error">
        {% if pw_mismatch %}
          <p style="color:red">パスワードが一致しません</p>
        {% elif user_exists %}
          <p style="color:red">そのユーザーは既に存在します。</p>
        {% elif invalid_fields %}
          <p style="color:red">すべてのフィールドが有効であることを確認してください。</p>
        {% endif %}
      </div>
      <div class="container">
        <div class="login-form">
          <form class="" action="{% url "Blog:Registration" %}" method="POST">
            {% csrf_token %}
            {{ registration_form|crispy }}
            <div class="login-submit-form"><input class="btn btn-primary" type="submit" name="" value="Submit"></div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Log-in form -->
  <div class="bg-modal login"
  {% if login_error %}
    style="display:flex"
  {% endif %}
  >
    <div class="modal-content">
      <div class="close">+</div>
      <div class="login-brand">
        <h2 class="blog-brand">ここでログイン</h2>
      </div>
      {% if login_error %}
      <div class="login-error">
          <p style="color:red">すべてのフィールドが有効であることを確認してください。</p>
      </div>
      {% endif %}
      <div class="login-form">
        <form class="" action="{% url "Blog:Login" %}" method="POST">
          {% csrf_token %}
          {{ login_form|crispy }}
          <div class="login-submit-form"><input class="btn btn-primary" type="submit" name="" value="Submit"></div>
        </form>
      </div>
      </div>
  </div>

  <!-- blog posts -->
  {% if blogposts|length == 0 %}
  <br>
  <br>
  <br>
    <div style = "margin-left: 18rem !important;margin-right: 15rem !important">
      <div class = "table-responsive">
        <table class = "table">     
        <tr>
          <th style="width:60%">
          <div class = "container blog-container" style="width:90% !important">
            <br>
            <br>
            <br>
            <div class="title_date">
              <div class="post_title">
                <h1>Webアプリケーションについて</h1>
              </div>
              <br>
              <div class="post_date">
                <h4> - 会社Xによって</h4>
              </div>
            </div>
            <br>
            <br>
            <br>
            <div class="photo_subtitle" style="font-weight: normal !important">
              これは会社とこのアプリに関する簡潔な紹介が含まれます。それによって提供される様々なサービスのように。たとえば、ユーザーはグラフを表示したり、各テレビ番組や自分のお気に入りの番組の傾向を比較したりできます。
            </div>
          </div>
          </th>
          <th style="width:40%">
          <div class = "container blog-container" style="width:80% !important">
          <div class = "post_image_wrapper" >
            

            <img class = "post_image" src="https://d1yn1kh78jj1rr.cloudfront.net/image/preview/rnp9KOKvfjdviiioz/storyblocks-pulse-graph-on-monitor-icon-in-simple-style-on-a-white-background_HEYTzz0sz_SB_PM.jpg" alt="Responsive image" style="width:30rem !important;height:25rem !important"/> 
          </div>
          </div>
          </th>
        </tr>
        </table>
      </div>
    </div>
  {% else %}

    {% for blogpost in blogposts %}
      <div class="container blog-container">
        <div class="title_date">
          <div class="post_title">
            <h1>{{ blogpost.title }}</h1>
          </div>
          <div class="post_date">
            <h4>{{ blogpost.posted_at }}</h4>
          </div>
        </div>
        <div class="post_image_wrapper">
          <img class="post_image" src="{{ blogpost.photo.url }}" alt="">
        </div>
        <div class="photo_subtitle">
          <p class="subtitle">{{ blogpost.photo_subtitle }}</p>
        </div>
        <div class="post_body">
          {{ blogpost.body|safe }}
        <hr>
        <h2>Join the discussion:</h2>
        <div class="text-editor">
          {% if user.is_authenticated %}
            <form class="comment-form" enctype="multipart/form-data" action="{% url "Blog:Blog_index" %}" method="post">
              {{ form.media }}
              {{ form|crispy }}
              {% csrf_token %}
              <div class="submit-comment">
                <input class="btn btn-primary comment-submit" type="submit" name="" value="Submit">
              </div>
            </form>
          {% else %}
            <p>Log in or Sign up to vote and leave comments.</p>
            <div class="row">
              <input class="btn btn-primary sign-up-btn" type="submit" name="" value="Sign up">
              <input class="btn btn-primary log-in-btn" type="submit" name="" value="Log in">
            </div>
          {% endif %}
        </div>

          <div class="comments-section">
          <!-- Comment Section  -->
          {% if blogpost.comments.all|length == 0 %}
              <hr>
              <div class="comments">
                <div class="comment-name-date">
                  <h6><strong>Cthulhu</strong> | June 24, 1994</h6>
                </div>
                <div class="comment-body">
                  Be the first to submit a comment!
                </div>
                <div class="vote-reply-score">
                  0
                  <a href="#"><i class="fas fa-chevron-up"></i></a>
                  |
                  <a href="#"><i class="fas fa-chevron-down"></i></a>
                  <a href="#">Reply</a>
                </div>
              </div>
          {% else %}
            {% include "Blog/comments.html" %}
          {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}

  {% endif %}

<div class="pagination">

  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}

      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <div class="current-page-num">
          <li><a href="?page={{ i }}"><span id="num">{{ i }}</span></a></li>
        </div>
        {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
      <div class="page-num">
          <li><a href="?page={{ i }}"><span id="num">{{ i }}</span></a></li>
      </div>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}

</div>

{% endblock %}