Blog/urls.py
from django.urls import path
from .views import (BlogIndexView, Login, LogOut, ReplyHandler, Registration,
                    UpdateDeleteComment, VotesHandler)

app_name = 'Blog'

urlpatterns = [
    path('',
        BlogIndexView.as_view(),
        name='Blog_index',
        ),
    path(
        'Comment/Delete/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Delete_comment',
        ),
    path(
        'Comment/Update/<int:comment_pk>/',
        UpdateDeleteComment,
        name='Update_comment',
        ),
    path(
        'Login/',
        Login.as_view(),
        name='Login',
        ),
    path(
        'Login/<str:error>/',
        BlogIndexView.as_view(),
        name="Login_error",
        ),
    path(
        'Logout/',
        LogOut.as_view(),
        name='Logout',
        ),
    path(
        'Reply/<str:parent_comment_pk>/',
        ReplyHandler,
        name='Reply',
        ),
    path(
        'Registration/',
        Registration,
        name='Registration',
        ),
    path(
        'Registration/<str:error_type>/',
         BlogIndexView.as_view(),
         name='Registration_error',
        ),
    path(
        'Vote/<int:comment_pk>/<str:vote_type>/',
        VotesHandler,
        name='Vote',
        ),
]

Profile/urls.py
from django.urls import path

from .views import upload_csv,IndexView, SubscriptionHandler, ResumeView, csv_download, load_product_data, SubscriptionHandler_product

app_name = 'Profile'

urlpatterns = [
    path(
        '',
        IndexView.as_view(),
        name='index',
        ),
    path(
        'BNResume/',
        ResumeView,
        name='resume',
        ),
    path(
        'Subscription/',
        SubscriptionHandler,
        name='subscription',
        ),
    path(
        'Product_Subscription/',
        SubscriptionHandler_product,
        name='product-subscription',
        ),
    path(
        'csv_download/',
        csv_download,
        name='csv_download',
        ),
    path(
        'load_product_data/',
        load_product_data,
        name='load_product_data',
        ),
    path(
        'upload_csv',
        upload_csv,
        name='upload_csv'
        ),
]

main_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
        ),
    path(
        '',
        include('Blog.urls'),
        ),
    path('profile/',
        include('Profile.urls'),
        ),
    path('custom_search/',
        include('custom_search.urls'),
        ),
    path('django_plotly_dash/', 
        include('django_plotly_dash.urls'),
        ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project X</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href= "{% static "slick/slick.css" %}"/>
  <link rel="stylesheet" type="text/css" href= "{% static "slick/slick-theme.css" %}"/>
  <link rel="stylesheet" href="{% static "css/tablebar.css" %}">
  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static "slick/slick.min.js" %}"></script>
  <script type="text/javascript">
    $(window).load(function() {
      // Animate loader off screens
      $(".loading").fadeOut("slow");
      $("body").fadeIn("slow");
    });
  </script>

  <!-- Custom styles for this template -->
  <link href="{% static "base/css/callofcthoder.css" %}" rel="stylesheet">
  
</head>
<div class="loading" style = "position: fixed;left: 0px;top: 0px;width: 100%;height:100%;z-index: 9999;background-image: url(https://media0.giphy.com/media/EIyuzZk6IDUMU/source.gif)"></div>

<body id="page-top" style="background-image: url(https://py-googletrans.readthedocs.io/en/latest/_static/subtle_dots.png);">
  

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav" style = "background:white;">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top" style="color:black">Project X</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        メニュー
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto" style="color:black;font-weight: 800">
          {% block navigation %}{% endblock %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Heading Section -->

{% block content %}{% endblock %}

  <!-- Signup Section -->
  <section id="signup" class="signup-section">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 mx-auto text-center">

          <h2 class="text-white mb-5 subscription-message">新しいブログエントリについて通知を受け取るために購読する！</h2>

          <form class="form-inline d-flex subscribe-form" action="{% url "Profile:subscription" %}" method="post">
            {% csrf_token %}
            <input name='user_email' type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" placeholder="Enter email address...">
            <button type="submit" class="btn btn-primary mx-auto subscribe-button">止める</button>
          </form>


        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="contact-section bg-black">
    <div class="container">

      <div class="row">

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fab fa-github-alt text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Github</h4>
              <hr class="my-4">
              <div class="small text-black-50"><a href="{{contact_info.github}}">{{contact_info.github}}</a></div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-envelope text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Email</h4>
              <hr class="my-4">
              <div class="small text-black-50">
                <span class="personal-email">{{ contact_info.email }}</span>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fab fa-linkedin-in text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">LinkedIn</h4>
              <hr class="my-4">
              <div class="small text-black-50"><a href="{{ contact_info.linkedin }}">{{ contact_info.linkedin }}</a></div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-black small text-center text-white-50">
    <div class="container">
      Copyright &copy; SMS DATA TECH 2019
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static "base/js/callofcthoder.min.js" %}"></script>

  <!-- Jquery CDN-->
  <script
  src="https://code.jquery.com/jquery-3.4.0.js"
  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
  crossorigin="anonymous"></script>

  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="{% static "slick/slick.min.js" %}"></script>
  <!-- Custom Jquery -->
  <script src="{% static "base/js/vote.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/comment.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/reply.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/reply_secondary.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/subscriptions.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/modal.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/delete_comment.js" %}" charset="utf-8"></script>
  <script src="{% static "base/js/edit_comment.js" %}" charset="utf-8"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
  <script>hljs.initHighlighting();</script>
  {% block scripts %}
  {% endblock %}
</body>

</html>

templates/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>hmmmmm</h1>
  </body>
</html>